import { supabase } from './supabase';

// ─────────────────────────────────────────
// Place a new order (called from checkout)
// ─────────────────────────────────────────
export const placeOrder = async (userId, { addressData, paymentMethod, cartItems }) => {
  try {
    const totalQuantity = cartItems.reduce((s, i) => s + i.quantity, 0);
    const totalSale = cartItems.reduce(
      (s, i) => s + (i.product?.discount_price || i.product?.original_price || i.product?.price || 0) * i.quantity,
      0
    );

    // Insert order row (invoice_number auto-generated by DB trigger)
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert([{
        user_id: userId,
        invoice_number: '',         // trigger fills this
        total_sale: totalSale,
        total_quantity: totalQuantity,
        delivery_address: addressData,
        payment_method: paymentMethod,
        payment_status: paymentMethod === 'cod' ? 'pending' : 'pending',
        status: 'pending'
      }])
      .select()
      .single();

    if (orderError) throw orderError;

    // Build order_items rows
    const items = cartItems.map((i) => ({
      order_id: order.id,
      product_id: i.productId || null,
      product_name: i.product?.name || 'Unknown Product',
      product_image: i.product?.image_url || null,
      product_code: i.product?.lookup_code || null,
      department: i.product?.item_details_data?.department || null,
      subcategory: i.product?.item_details_data?.subcategory || null,
      unit_price: i.product?.discount_price || i.product?.original_price || i.product?.price || 0,
      original_price: i.product?.original_price || null,
      quantity: i.quantity,
      customization: i.customization || {},
      printing_time: i.product?.printing_time || null
    }));

    const { error: itemsError } = await supabase
      .from('order_items')
      .insert(items);

    if (itemsError) throw itemsError;

    return { data: order, error: null };
  } catch (error) {
    return { data: null, error };
  }
};

// ─────────────────────────────────────────
// Get orders for a specific user
// ─────────────────────────────────────────
export const getUserOrders = async (userId) => {
  try {
    const { data, error } = await supabase
      .from('orders')
      .select(`
        *,
        order_items (*)
      `)
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    return { data: null, error };
  }
};

// ─────────────────────────────────────────
// Get ALL orders (admin only)
// ─────────────────────────────────────────
export const getAllOrders = async () => {
  try {
    const { data, error } = await supabase
      .from('orders')
      .select(`
        *,
        order_items (*)
      `)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    return { data: null, error };
  }
};

// ─────────────────────────────────────────
// Update order status (admin)
// ─────────────────────────────────────────
export const updateOrderStatus = async (orderId, status, adminNotes = null, estimatedDelivery = null) => {
  try {
    const updates = { status };
    if (adminNotes !== null) updates.admin_notes = adminNotes;
    if (estimatedDelivery !== null) updates.estimated_delivery = estimatedDelivery;

    const { data, error } = await supabase
      .from('orders')
      .update(updates)
      .eq('id', orderId)
      .select()
      .single();

    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    return { data: null, error };
  }
};
